### ISSUE TITLE
"Address already in use" when running both client and server

### ISSUE THREAD

**Issue by vjdw** [christf/snapcastc#20]
With snapcast I run snapclient on the same host as snapserver. When I try this with snapcastc then snapcast-client gives an error and exits ```bind socket to node-IP failed: Address already in use```.

**Comment by christf** [comment]
On Mon, Feb 25, 2019 at 09:38:45PM +0000, Vince wrote:
>With snapcast I run snapclient on the same host as snapserver. When I 
>try this with snapcastc then snapcast-client gives an error and exits 
>```bind socket to node-IP failed: Address already in use```.
Yes. Both will bind to the same port. When adjusting the local port for 
the client using -P like ./tools/runsnapclient:
./src/snapcast-client -H localhost -p 1705 -s default

**Comment by christf** [comment]
Where you able to resolve the issue with the input that was provided? In any case, proper initialization for systemd and packaging will have to happen.

**Comment by vjdw** [comment]
Yes thanks, that is working now. I do get a lot of timing errors, even though client and server are on the same host, but that's another issue :)

```Timing is not even close, we are ahead by 0.034438000 seconds: replacing data with silence```

**Comment by christf** [comment]
That usually is a symptom of the wrong sample rate. snapcastc is not yet tested with 44100Hz however from this message it looks like you are feeding thata at that rate. Also, I am reworking the handling of sample rate in #13 AT one point snapcastc should support multiple sample rates besides 48KHz. However the usage of opus will lead to this being the only allowed rate for now.

**Comment by christf** [comment]
ah, I see. It also is a symptom of the client for some reason stopping to send hello messages to the server. The server will eventually drop the client and stop sending data. I do not know the reason yet but there is something wrong there.

**Comment by christf** [comment]
the originally posted issue was resolved - clients now chose a random port. Please open another issue if there are other symptoms.
