### ISSUE TITLE
minor issue with mpd config example in Readme

### ISSUE THREAD

**Issue by pccasto** [christf/snapcastc#23]
Hi Christof,

I'm still using snapcast, and haven't tried your snapcastc yet - but will one of these days :-). It looks interesting.

Noticed that the example you gave for mpd configuration with pipe output has the parameters capitalized.  My version of mpd (v0.21.4) throws errors and fails to start unless parameters are in lower case, as follows
``` 
audio_output {
        type            "pipe"
        name            "snapcast"
        command         "cat >/tmp/snapfifo"
        format          "48000:16:2"
        auto_resample   "no"
}
```

Thanks again for your project.
~paul

**Comment by christf** [comment]
Thank youfor reporting that - this is indeed an issue. My editor was trying to be helpful by capitalizing these words...

This should be fixed now.

**Comment by pccasto** [comment]
"damn you, auto-correct..."  I thought that might be the case.

I was just happy to find your explanation of the pro's and con's of pipe -vs- fifo from mpd.
